exclude:
  - node_modules
encoding: UTF-8
markdown: kramdown # GMF
include:
  - assets
plugins:
  - jemoji
google_analytics: G-HFNEYKB0G4
nav:
  - text: Home
    icon: home
    permalink: ./
  - text: Matricole
    icon: school
    permalink: matricole
  - text: Percorso Formativo
    icon: conversion_path
    permalink: percorso-formativo
  - text: Tirocinio
    icon: lab_research
    permalink: tirocinio
  - text: Laurea
    icon: description
    permalink: laurea
  - text: Risorse
    icon: folder_open
    permalink: risorse
  - text: Gruppi
    icon: group
    permalink: gruppi
  - text: Orari
    icon: schedule
    permalink: orari
  - text: Orari ACSAI
    icon: alarm
    permalink: orari/acsai
  - text: Orario Custom
    icon: calendar_today
    permalink: orario
  # - text:
  #   icon:
  #   permalink:
