title = 'sapienzastudents.net'
theme = 'hugo-book'
defaultContentLanguage = 'homepage'
defaultContentLanguageInSubdir = false
enableGitInfo = true
custom_css = ["css/contributors.css"]

[languages]
    [languages.homepage]
        BookSearch = false
        contentDir = 'homepage'
        languageName = 'Degree Programme Choice'
        title = "Homepage"
        weight = 0

        [languages.homepage.params]
            contentDir = 'homepage'

    [languages.30786]
        contentDir = '30786'
        disabled = false
        languageName = 'ACSAI'
        title = 'ACSAI'
        weight = 1

        [languages.30786.params]
            contentDir = '30786'

    [languages.29932]
        contentDir = '29932'
        disabled = false
        languageName = 'Computer Science'
        title = 'Computer Science'
        weight = 2

        [languages.29932.params]
            contentDir = '29932'

    [languages.it]
        contentDir = 'it'
        disabled = false
        languageName = 'Informatica'
        title = 'Informatica'
        weight = 3

        [languages.it.params]
            contentDir = 'it'

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true

                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)'], ['$', '$']]

        [markup.goldmark.renderer]
            unsafe = true

[params]
    math = true
    BookTheme = 'auto'
    BookToC = true
    BookLogo = 'logo.png'
    #BookSection = '*'
    BookSection = '*'

    # GitHub Stuff
    BookRepo = 'https://github.com/sapienzastudentsnetwork/sapienzastudentsnetwork.github.io'
    BookCommitPath = 'commit'
    BookEditPath = 'edit/main'
    BookDateFormat = '2 January 2006'
